// <auto-generated />
using ID3.Finance.Binance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ID3.Finance.Binance.Migrations
{
    [DbContext(typeof(BinanceContext))]
    [Migration("20231117171644_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ID3.Finance.Binance.Models.BinanceModels.BinanceKlineResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAssetVolume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Close")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("High")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Low")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Open")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteAssetVolume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeightedAveragePrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KlineResults");
                });
#pragma warning restore 612, 618
        }
    }
}
